# Generated by Django 3.1.4 on 2022-12-13 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telainicial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pet',
            table='pet_lost',
        ),
    ]
