# Generated by Django 3.1.4 on 2022-12-10 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telainicial', '0002_auto_20221210_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pets',
            old_name='descrição',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='pets',
            old_name='espécie',
            new_name='especie',
        ),
        migrations.RenameField(
            model_name='pets',
            old_name='raça',
            new_name='raca',
        ),
    ]
