# Generated by Django 3.1.4 on 2022-12-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telainicial', '0002_auto_20221212_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='begin_date',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='end_date',
        ),
        migrations.AddField(
            model_name='pet',
            name='castrado',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='especie',
            field=models.CharField(choices=[('Cão', 'Cão'), ('Gato', 'Gato')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='idade',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='porte',
            field=models.CharField(choices=[('XP', 'Mini'), ('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande'), ('XG', 'Extra Grande')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='raca',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='nome',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterModelTable(
            name='pet',
            table='ficha_pet',
        ),
    ]
