# Generated by Django 3.1.4 on 2022-12-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telainicial', '0003_auto_20221210_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='especie',
            field=models.CharField(choices=[('Cão', 'Cão'), ('Gato', 'Gato')], max_length=4),
        ),
    ]
