# Generated by Django 4.1.4 on 2022-12-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telainicial', '0004_auto_20221213_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, null=True)),
                ('conteudo', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'noticia',
            },
        ),
        migrations.AddField(
            model_name='pet',
            name='bairro',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
